name: Build the container image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - published
  workflow_dispatch:

env:
  image_name: ghcr.io/${{ github.repository_owner }}/caddy-lego
  platforms: linux/amd64,linux/arm64

jobs:
  build:
    name: Build the container image
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: docker/login-action@v3
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}

      - name: Build the container image
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ env.platforms }}
          tags: ${{ env.image_name }}:latest

      - name: Build and push latest image to registry
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          platforms: ${{ env.platforms }}
          push: true
          tags: ${{ env.image_name }}:latest

      - name: Build and push release image to registry
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          platforms: ${{ env.platforms }}
          push: true
          tags: |
            ${{ env.image_name }}:latest
            ${{ env.image_name }}:${{ github.event.release.tag_name }}
